
server:
  port: 8120

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: replica2
  client:
    # 是否从注册中心获取服务
    register-with-eureka: true
    # 是否将服务注册到注册中心
    fetch-registry: true
    service-url:
      # 注册到另一个Eureka注册中心，如果认证添加帐号密码
#      defaultZone: http://replica1:8110/eureka
      defaultZone: http://admin:admin@replica1:8110/eureka
