
server:
  port: 8202

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:4306/seata-order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # druid配置
    druid:
      # 初始化大小
      initial-size: 5
      # 最小
      min-idle: 10
      # 最大
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 6000
  cloud:
    nacos:
      discovery:
        # nacos地址
        server-addr: 192.168.110.40:8848
        group: SEATA_GROUP

seata:
  enabled: true
  application-id: ${spring.application.name}
  # 分组名
  tx-service-group: seata_tx_group
  service:
    vgroup-mapping:
      # 分组名，值为TC集群名
      seata_tx_group: seata-server-cluster
  # 配置中心地址
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.110.40:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
  # 注册中心地址
  registry:
    type: nacos
    nacos:
      # Server和Client端的值需一致
      application: seata-server
      server-addr: 192.168.110.40:8848
      group : SEATA_GROUP
      namespace:
      username: nacos
      password: nacos

mybatis:
  typeAliasesPackage: com.shpun.model
  mapper-locations: classpath:mapper/**.xml