
server:
  port: 8101

spring:
  application:
    name: eureka-client-1

eureka:
  client:
    service-url:
      # 独立模式
#      defaultZone: http://localhost:8100/eureka
      # 多注册中心
#      defaultZone: http://replica1:8110/eureka
      # 注册中心加认证 按格式添加帐号密码 http://${username}:${password}@${hostname}:${port}/eureka/
        defaultZone: http://admin:admin@localhost:8100/eureka