
server:
  port: 8200

spring:
  application:
    name: ribbon-service
  cloud:
    consul:
      # 将服务注册到consul
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 指定主机名，防止主机名出现不规范字符
        hostname: localhost

service-url:
  user-service: http://user-service

# 全局配置
ribbon:
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 1000
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 3000
  # 对超时请求启用重试机制
  OkToRetryOnAllOperations: true
  # 切换重试实例的最大个数
  MaxAutoRetriesNextServer: 1
  # 切换实例后重试最大次数
  MaxAutoRetries: 1
  # 修改负载均衡算法
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 指定应用进行配置
user-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  level:
    com.shpun: debug