
server:
  port: 8300

spring:
  application:
    name: zuul-proxy

eureka:
  instance:
    # 是否优先使用ip来作为主机名
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

zuul:
  #打开重试机制
  retryable: true
  # 网关路由添加前缀，添加前缀后一直404，未解决
  #prefix: /proxy
  # 过滤敏感的请求头信息，防止丢失，设置为空就不会过滤
  sensitive-headers: Cookie,Set-Cookie,Authorization
  # 重定向是会添加host请求头
  add-host-header: true
  # 关闭默认路由配置，使用服务名就访问不到
  ignored-services: user-service,openfeign-service
  # 为服务配置路由
  routes:
    # 将所有/user/** 映射到 user-service 服务中去
    user-service:
      path: /user/**
      serviceId: user-service
      # 网关路由添加前缀，需要设置为false
      #stripPrefix: false
    openfeign-service:
      path: /feign/**
      serviceId: openfeign-service

hystrix:
  # 用于控制HystrixCommand的行为
  command:
    default:
      execution:
        isolation:
          thread:
            # 配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
            # Hystrix设置的超时时间要比Ribbon设置的超时时间短。
            timeoutInMilliseconds: 6000

# 超时时间：(2000+1000)*(0+1)*(1+1)=6000：
ribbon:
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 1000
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 3000
  # 最大重试次数
  MaxAutoRetries: 0
  # 最大重试服务个数
  MaxAutoRetriesNextServer: 0

logging:
  level:
    com.shpun: debug